/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Timestamp = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PrescriptionInput = IDL.Record({
  'endDate' : IDL.Opt(Timestamp),
  'documentRef' : IDL.Opt(ExternalBlob),
  'dosage' : IDL.Text,
  'notes' : IDL.Text,
  'frequency' : IDL.Text,
  'startDate' : Timestamp,
  'medicineName' : IDL.Text,
});
export const RecordId = IDL.Nat;
export const PrescriptionStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Prescription = IDL.Record({
  'id' : RecordId,
  'status' : PrescriptionStatus,
  'endDate' : IDL.Opt(Timestamp),
  'documentRef' : IDL.Opt(ExternalBlob),
  'dosage' : IDL.Text,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'notes' : IDL.Text,
  'frequency' : IDL.Text,
  'startDate' : Timestamp,
  'medicineName' : IDL.Text,
});
export const ReportType = IDL.Variant({
  'lab' : IDL.Null,
  'other' : IDL.Null,
  'imaging' : IDL.Null,
});
export const ReportInput = IDL.Record({
  'reportDate' : Timestamp,
  'reportType' : ReportType,
  'notes' : IDL.Text,
  'fileRef' : ExternalBlob,
});
export const Report = IDL.Record({
  'id' : RecordId,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'reportDate' : Timestamp,
  'reportType' : ReportType,
  'notes' : IDL.Text,
  'fileRef' : ExternalBlob,
});
export const ReminderInput = IDL.Record({
  'dosage' : IDL.Text,
  'reminderTimes' : IDL.Vec(IDL.Nat),
  'medicineName' : IDL.Text,
});
export const Reminder = IDL.Record({
  'id' : RecordId,
  'dosage' : IDL.Text,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'reminderTimes' : IDL.Vec(IDL.Nat),
  'isActive' : IDL.Bool,
  'medicineName' : IDL.Text,
});
export const FollowUpStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'rescheduled' : IDL.Null,
  'completed' : IDL.Null,
});
export const FollowUp = IDL.Record({
  'id' : RecordId,
  'status' : FollowUpStatus,
  'scheduledDate' : Timestamp,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'rescheduledDate' : IDL.Opt(Timestamp),
  'notes' : IDL.Text,
  'doctorName' : IDL.Text,
  'department' : IDL.Text,
});
export const DashboardSummary = IDL.Record({
  'todayReminders' : IDL.Vec(Reminder),
  'recentReports' : IDL.Vec(Report),
  'activePrescriptions' : IDL.Vec(Prescription),
  'upcomingFollowUps' : IDL.Vec(FollowUp),
});
export const DoseRecord = IDL.Record({
  'id' : RecordId,
  'reminderId' : RecordId,
  'owner' : UserId,
  'date' : Timestamp,
  'hour' : IDL.Nat,
  'takenAt' : Timestamp,
});
export const TimelineEventKind = IDL.Variant({
  'report' : IDL.Record({
    'reportType' : IDL.Variant({
      'lab' : IDL.Null,
      'other' : IDL.Null,
      'imaging' : IDL.Null,
    }),
    'notes' : IDL.Text,
    'fileRef' : ExternalBlob,
  }),
  'prescription' : IDL.Record({
    'status' : IDL.Variant({ 'active' : IDL.Null, 'inactive' : IDL.Null }),
    'dosage' : IDL.Text,
    'frequency' : IDL.Text,
    'medicineName' : IDL.Text,
  }),
  'followup' : IDL.Record({
    'status' : IDL.Variant({
      'scheduled' : IDL.Null,
      'rescheduled' : IDL.Null,
      'completed' : IDL.Null,
    }),
    'doctorName' : IDL.Text,
    'department' : IDL.Text,
  }),
});
export const TimelineEvent = IDL.Record({
  'id' : RecordId,
  'date' : Timestamp,
  'kind' : TimelineEventKind,
});
export const FollowUpInput = IDL.Record({
  'scheduledDate' : Timestamp,
  'notes' : IDL.Text,
  'doctorName' : IDL.Text,
  'department' : IDL.Text,
});
export const ReminderUpdate = IDL.Record({
  'dosage' : IDL.Opt(IDL.Text),
  'reminderTimes' : IDL.Opt(IDL.Vec(IDL.Nat)),
  'isActive' : IDL.Opt(IDL.Bool),
  'medicineName' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addPrescription' : IDL.Func([PrescriptionInput], [Prescription], []),
  'addReport' : IDL.Func([ReportInput], [Report], []),
  'createReminder' : IDL.Func([ReminderInput], [Reminder], []),
  'deleteFollowUp' : IDL.Func([RecordId], [IDL.Bool], []),
  'deleteReminder' : IDL.Func([RecordId], [IDL.Bool], []),
  'deleteReport' : IDL.Func([RecordId], [IDL.Bool], []),
  'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
  'getDoseHistory7Days' : IDL.Func(
      [Timestamp],
      [IDL.Vec(DoseRecord)],
      ['query'],
    ),
  'getHealthTimeline' : IDL.Func([], [IDL.Vec(TimelineEvent)], ['query']),
  'getPrescription' : IDL.Func([RecordId], [IDL.Opt(Prescription)], ['query']),
  'getReport' : IDL.Func([RecordId], [IDL.Opt(Report)], ['query']),
  'getUpcomingFollowUps' : IDL.Func(
      [Timestamp],
      [IDL.Vec(FollowUp)],
      ['query'],
    ),
  'listActiveReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
  'listFollowUps' : IDL.Func([], [IDL.Vec(FollowUp)], ['query']),
  'listPrescriptions' : IDL.Func([], [IDL.Vec(Prescription)], ['query']),
  'listReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'markFollowUpCompleted' : IDL.Func([RecordId], [IDL.Bool], []),
  'recordDoseTaken' : IDL.Func(
      [RecordId, Timestamp, IDL.Nat],
      [DoseRecord],
      [],
    ),
  'rescheduleFollowUp' : IDL.Func([RecordId, Timestamp], [IDL.Bool], []),
  'scheduleFollowUp' : IDL.Func([FollowUpInput], [FollowUp], []),
  'updatePrescriptionStatus' : IDL.Func(
      [RecordId, PrescriptionStatus],
      [IDL.Bool],
      [],
    ),
  'updateReminder' : IDL.Func([RecordId, ReminderUpdate], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Timestamp = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PrescriptionInput = IDL.Record({
    'endDate' : IDL.Opt(Timestamp),
    'documentRef' : IDL.Opt(ExternalBlob),
    'dosage' : IDL.Text,
    'notes' : IDL.Text,
    'frequency' : IDL.Text,
    'startDate' : Timestamp,
    'medicineName' : IDL.Text,
  });
  const RecordId = IDL.Nat;
  const PrescriptionStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Prescription = IDL.Record({
    'id' : RecordId,
    'status' : PrescriptionStatus,
    'endDate' : IDL.Opt(Timestamp),
    'documentRef' : IDL.Opt(ExternalBlob),
    'dosage' : IDL.Text,
    'owner' : UserId,
    'createdAt' : Timestamp,
    'notes' : IDL.Text,
    'frequency' : IDL.Text,
    'startDate' : Timestamp,
    'medicineName' : IDL.Text,
  });
  const ReportType = IDL.Variant({
    'lab' : IDL.Null,
    'other' : IDL.Null,
    'imaging' : IDL.Null,
  });
  const ReportInput = IDL.Record({
    'reportDate' : Timestamp,
    'reportType' : ReportType,
    'notes' : IDL.Text,
    'fileRef' : ExternalBlob,
  });
  const Report = IDL.Record({
    'id' : RecordId,
    'owner' : UserId,
    'createdAt' : Timestamp,
    'reportDate' : Timestamp,
    'reportType' : ReportType,
    'notes' : IDL.Text,
    'fileRef' : ExternalBlob,
  });
  const ReminderInput = IDL.Record({
    'dosage' : IDL.Text,
    'reminderTimes' : IDL.Vec(IDL.Nat),
    'medicineName' : IDL.Text,
  });
  const Reminder = IDL.Record({
    'id' : RecordId,
    'dosage' : IDL.Text,
    'owner' : UserId,
    'createdAt' : Timestamp,
    'reminderTimes' : IDL.Vec(IDL.Nat),
    'isActive' : IDL.Bool,
    'medicineName' : IDL.Text,
  });
  const FollowUpStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'rescheduled' : IDL.Null,
    'completed' : IDL.Null,
  });
  const FollowUp = IDL.Record({
    'id' : RecordId,
    'status' : FollowUpStatus,
    'scheduledDate' : Timestamp,
    'owner' : UserId,
    'createdAt' : Timestamp,
    'rescheduledDate' : IDL.Opt(Timestamp),
    'notes' : IDL.Text,
    'doctorName' : IDL.Text,
    'department' : IDL.Text,
  });
  const DashboardSummary = IDL.Record({
    'todayReminders' : IDL.Vec(Reminder),
    'recentReports' : IDL.Vec(Report),
    'activePrescriptions' : IDL.Vec(Prescription),
    'upcomingFollowUps' : IDL.Vec(FollowUp),
  });
  const DoseRecord = IDL.Record({
    'id' : RecordId,
    'reminderId' : RecordId,
    'owner' : UserId,
    'date' : Timestamp,
    'hour' : IDL.Nat,
    'takenAt' : Timestamp,
  });
  const TimelineEventKind = IDL.Variant({
    'report' : IDL.Record({
      'reportType' : IDL.Variant({
        'lab' : IDL.Null,
        'other' : IDL.Null,
        'imaging' : IDL.Null,
      }),
      'notes' : IDL.Text,
      'fileRef' : ExternalBlob,
    }),
    'prescription' : IDL.Record({
      'status' : IDL.Variant({ 'active' : IDL.Null, 'inactive' : IDL.Null }),
      'dosage' : IDL.Text,
      'frequency' : IDL.Text,
      'medicineName' : IDL.Text,
    }),
    'followup' : IDL.Record({
      'status' : IDL.Variant({
        'scheduled' : IDL.Null,
        'rescheduled' : IDL.Null,
        'completed' : IDL.Null,
      }),
      'doctorName' : IDL.Text,
      'department' : IDL.Text,
    }),
  });
  const TimelineEvent = IDL.Record({
    'id' : RecordId,
    'date' : Timestamp,
    'kind' : TimelineEventKind,
  });
  const FollowUpInput = IDL.Record({
    'scheduledDate' : Timestamp,
    'notes' : IDL.Text,
    'doctorName' : IDL.Text,
    'department' : IDL.Text,
  });
  const ReminderUpdate = IDL.Record({
    'dosage' : IDL.Opt(IDL.Text),
    'reminderTimes' : IDL.Opt(IDL.Vec(IDL.Nat)),
    'isActive' : IDL.Opt(IDL.Bool),
    'medicineName' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addPrescription' : IDL.Func([PrescriptionInput], [Prescription], []),
    'addReport' : IDL.Func([ReportInput], [Report], []),
    'createReminder' : IDL.Func([ReminderInput], [Reminder], []),
    'deleteFollowUp' : IDL.Func([RecordId], [IDL.Bool], []),
    'deleteReminder' : IDL.Func([RecordId], [IDL.Bool], []),
    'deleteReport' : IDL.Func([RecordId], [IDL.Bool], []),
    'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
    'getDoseHistory7Days' : IDL.Func(
        [Timestamp],
        [IDL.Vec(DoseRecord)],
        ['query'],
      ),
    'getHealthTimeline' : IDL.Func([], [IDL.Vec(TimelineEvent)], ['query']),
    'getPrescription' : IDL.Func(
        [RecordId],
        [IDL.Opt(Prescription)],
        ['query'],
      ),
    'getReport' : IDL.Func([RecordId], [IDL.Opt(Report)], ['query']),
    'getUpcomingFollowUps' : IDL.Func(
        [Timestamp],
        [IDL.Vec(FollowUp)],
        ['query'],
      ),
    'listActiveReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
    'listFollowUps' : IDL.Func([], [IDL.Vec(FollowUp)], ['query']),
    'listPrescriptions' : IDL.Func([], [IDL.Vec(Prescription)], ['query']),
    'listReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'markFollowUpCompleted' : IDL.Func([RecordId], [IDL.Bool], []),
    'recordDoseTaken' : IDL.Func(
        [RecordId, Timestamp, IDL.Nat],
        [DoseRecord],
        [],
      ),
    'rescheduleFollowUp' : IDL.Func([RecordId, Timestamp], [IDL.Bool], []),
    'scheduleFollowUp' : IDL.Func([FollowUpInput], [FollowUp], []),
    'updatePrescriptionStatus' : IDL.Func(
        [RecordId, PrescriptionStatus],
        [IDL.Bool],
        [],
      ),
    'updateReminder' : IDL.Func([RecordId, ReminderUpdate], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };