/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardSummary {
  'todayReminders' : Array<Reminder>,
  'recentReports' : Array<Report>,
  'activePrescriptions' : Array<Prescription>,
  'upcomingFollowUps' : Array<FollowUp>,
}
export interface DoseRecord {
  'id' : RecordId,
  'reminderId' : RecordId,
  'owner' : UserId,
  'date' : Timestamp,
  'hour' : bigint,
  'takenAt' : Timestamp,
}
export type ExternalBlob = Uint8Array;
export interface FollowUp {
  'id' : RecordId,
  'status' : FollowUpStatus,
  'scheduledDate' : Timestamp,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'rescheduledDate' : [] | [Timestamp],
  'notes' : string,
  'doctorName' : string,
  'department' : string,
}
export interface FollowUpInput {
  'scheduledDate' : Timestamp,
  'notes' : string,
  'doctorName' : string,
  'department' : string,
}
export type FollowUpStatus = { 'scheduled' : null } |
  { 'rescheduled' : null } |
  { 'completed' : null };
export interface Prescription {
  'id' : RecordId,
  'status' : PrescriptionStatus,
  'endDate' : [] | [Timestamp],
  'documentRef' : [] | [ExternalBlob],
  'dosage' : string,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'notes' : string,
  'frequency' : string,
  'startDate' : Timestamp,
  'medicineName' : string,
}
export interface PrescriptionInput {
  'endDate' : [] | [Timestamp],
  'documentRef' : [] | [ExternalBlob],
  'dosage' : string,
  'notes' : string,
  'frequency' : string,
  'startDate' : Timestamp,
  'medicineName' : string,
}
export type PrescriptionStatus = { 'active' : null } |
  { 'inactive' : null };
export type RecordId = bigint;
export interface Reminder {
  'id' : RecordId,
  'dosage' : string,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'reminderTimes' : Array<bigint>,
  'isActive' : boolean,
  'medicineName' : string,
}
export interface ReminderInput {
  'dosage' : string,
  'reminderTimes' : Array<bigint>,
  'medicineName' : string,
}
export interface ReminderUpdate {
  'dosage' : [] | [string],
  'reminderTimes' : [] | [Array<bigint>],
  'isActive' : [] | [boolean],
  'medicineName' : [] | [string],
}
export interface Report {
  'id' : RecordId,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'reportDate' : Timestamp,
  'reportType' : ReportType,
  'notes' : string,
  'fileRef' : ExternalBlob,
}
export interface ReportInput {
  'reportDate' : Timestamp,
  'reportType' : ReportType,
  'notes' : string,
  'fileRef' : ExternalBlob,
}
export type ReportType = { 'lab' : null } |
  { 'other' : null } |
  { 'imaging' : null };
export interface TimelineEvent {
  'id' : RecordId,
  'date' : Timestamp,
  'kind' : TimelineEventKind,
}
export type TimelineEventKind = {
    'report' : {
      'reportType' : { 'lab' : null } |
        { 'other' : null } |
        { 'imaging' : null },
      'notes' : string,
      'fileRef' : ExternalBlob,
    }
  } |
  {
    'prescription' : {
      'status' : { 'active' : null } |
        { 'inactive' : null },
      'dosage' : string,
      'frequency' : string,
      'medicineName' : string,
    }
  } |
  {
    'followup' : {
      'status' : { 'scheduled' : null } |
        { 'rescheduled' : null } |
        { 'completed' : null },
      'doctorName' : string,
      'department' : string,
    }
  };
export type Timestamp = bigint;
export type UserId = Principal;
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addPrescription' : ActorMethod<[PrescriptionInput], Prescription>,
  'addReport' : ActorMethod<[ReportInput], Report>,
  'createReminder' : ActorMethod<[ReminderInput], Reminder>,
  'deleteFollowUp' : ActorMethod<[RecordId], boolean>,
  'deleteReminder' : ActorMethod<[RecordId], boolean>,
  'deleteReport' : ActorMethod<[RecordId], boolean>,
  'getDashboardSummary' : ActorMethod<[], DashboardSummary>,
  'getDoseHistory7Days' : ActorMethod<[Timestamp], Array<DoseRecord>>,
  'getHealthTimeline' : ActorMethod<[], Array<TimelineEvent>>,
  'getPrescription' : ActorMethod<[RecordId], [] | [Prescription]>,
  'getReport' : ActorMethod<[RecordId], [] | [Report]>,
  'getUpcomingFollowUps' : ActorMethod<[Timestamp], Array<FollowUp>>,
  'listActiveReminders' : ActorMethod<[], Array<Reminder>>,
  'listFollowUps' : ActorMethod<[], Array<FollowUp>>,
  'listPrescriptions' : ActorMethod<[], Array<Prescription>>,
  'listReports' : ActorMethod<[], Array<Report>>,
  'markFollowUpCompleted' : ActorMethod<[RecordId], boolean>,
  'recordDoseTaken' : ActorMethod<[RecordId, Timestamp, bigint], DoseRecord>,
  'rescheduleFollowUp' : ActorMethod<[RecordId, Timestamp], boolean>,
  'scheduleFollowUp' : ActorMethod<[FollowUpInput], FollowUp>,
  'updatePrescriptionStatus' : ActorMethod<
    [RecordId, PrescriptionStatus],
    boolean
  >,
  'updateReminder' : ActorMethod<[RecordId, ReminderUpdate], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];