/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface ReportInput {
    reportDate: Timestamp;
    reportType: ReportType;
    notes: string;
    fileRef: ExternalBlob;
}
export interface PrescriptionInput {
    endDate?: Timestamp;
    documentRef?: ExternalBlob;
    dosage: string;
    notes: string;
    frequency: string;
    startDate: Timestamp;
    medicineName: string;
}
export interface FollowUpInput {
    scheduledDate: Timestamp;
    notes: string;
    doctorName: string;
    department: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type TimelineEventKind = {
    __kind__: "report";
    report: {
        reportType: Variant_lab_other_imaging;
        notes: string;
        fileRef: ExternalBlob;
    };
} | {
    __kind__: "prescription";
    prescription: {
        status: PrescriptionStatus;
        dosage: string;
        frequency: string;
        medicineName: string;
    };
} | {
    __kind__: "followup";
    followup: {
        status: Variant_scheduled_rescheduled_completed;
        doctorName: string;
        department: string;
    };
};
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ReminderInput {
    dosage: string;
    reminderTimes: Array<bigint>;
    medicineName: string;
}
export interface Report {
    id: RecordId;
    owner: UserId;
    createdAt: Timestamp;
    reportDate: Timestamp;
    reportType: ReportType;
    notes: string;
    fileRef: ExternalBlob;
}
export interface ReminderUpdate {
    dosage?: string;
    reminderTimes?: Array<bigint>;
    isActive?: boolean;
    medicineName?: string;
}
export type RecordId = bigint;
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type UserId = Principal;
export interface TimelineEvent {
    id: RecordId;
    date: Timestamp;
    kind: TimelineEventKind;
}
export interface DoseRecord {
    id: RecordId;
    reminderId: RecordId;
    owner: UserId;
    date: Timestamp;
    hour: bigint;
    takenAt: Timestamp;
}
export interface Reminder {
    id: RecordId;
    dosage: string;
    owner: UserId;
    createdAt: Timestamp;
    reminderTimes: Array<bigint>;
    isActive: boolean;
    medicineName: string;
}
export interface DashboardSummary {
    todayReminders: Array<Reminder>;
    recentReports: Array<Report>;
    activePrescriptions: Array<Prescription>;
    upcomingFollowUps: Array<FollowUp>;
}
export interface FollowUp {
    id: RecordId;
    status: FollowUpStatus;
    scheduledDate: Timestamp;
    owner: UserId;
    createdAt: Timestamp;
    rescheduledDate?: Timestamp;
    notes: string;
    doctorName: string;
    department: string;
}
export interface Prescription {
    id: RecordId;
    status: PrescriptionStatus;
    endDate?: Timestamp;
    documentRef?: ExternalBlob;
    dosage: string;
    owner: UserId;
    createdAt: Timestamp;
    notes: string;
    frequency: string;
    startDate: Timestamp;
    medicineName: string;
}
export enum PrescriptionStatus {
    active = "active",
    inactive = "inactive"
}
export enum Variant_lab_other_imaging {
    lab = "lab",
    other = "other",
    imaging = "imaging"
}
export enum Variant_scheduled_rescheduled_completed {
    scheduled = "scheduled",
    rescheduled = "rescheduled",
    completed = "completed"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    addPrescription(input: PrescriptionInput): Promise<Prescription>;
    addReport(input: ReportInput): Promise<Report>;
    createReminder(input: ReminderInput): Promise<Reminder>;
    deleteFollowUp(id: RecordId): Promise<boolean>;
    deleteReminder(id: RecordId): Promise<boolean>;
    deleteReport(id: RecordId): Promise<boolean>;
    getDashboardSummary(): Promise<DashboardSummary>;
    getDoseHistory7Days(sinceTimestamp: Timestamp): Promise<Array<DoseRecord>>;
    getHealthTimeline(): Promise<Array<TimelineEvent>>;
    getPrescription(id: RecordId): Promise<Prescription | null>;
    getReport(id: RecordId): Promise<Report | null>;
    getUpcomingFollowUps(nowTimestamp: Timestamp): Promise<Array<FollowUp>>;
    listActiveReminders(): Promise<Array<Reminder>>;
    listFollowUps(): Promise<Array<FollowUp>>;
    listPrescriptions(): Promise<Array<Prescription>>;
    listReports(): Promise<Array<Report>>;
    markFollowUpCompleted(id: RecordId): Promise<boolean>;
    recordDoseTaken(reminderId: RecordId, date: Timestamp, hour: bigint): Promise<DoseRecord>;
    rescheduleFollowUp(id: RecordId, newDate: Timestamp): Promise<boolean>;
    scheduleFollowUp(input: FollowUpInput): Promise<FollowUp>;
    updatePrescriptionStatus(id: RecordId, status: PrescriptionStatus): Promise<boolean>;
    updateReminder(id: RecordId, updates: ReminderUpdate): Promise<boolean>;
}
import type { DashboardSummary as _DashboardSummary, ExternalBlob as _ExternalBlob, FollowUp as _FollowUp, FollowUpStatus as _FollowUpStatus, Prescription as _Prescription, PrescriptionInput as _PrescriptionInput, PrescriptionStatus as _PrescriptionStatus, RecordId as _RecordId, Reminder as _Reminder, ReminderUpdate as _ReminderUpdate, Report as _Report, ReportInput as _ReportInput, ReportType as _ReportType, TimelineEvent as _TimelineEvent, TimelineEventKind as _TimelineEventKind, Timestamp as _Timestamp, UserId as _UserId, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addPrescription(arg0: PrescriptionInput): Promise<Prescription> {
        if (this.processError) {
            try {
                const result = await this.actor.addPrescription(await to_candid_PrescriptionInput_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Prescription_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPrescription(await to_candid_PrescriptionInput_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Prescription_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async addReport(arg0: ReportInput): Promise<Report> {
        if (this.processError) {
            try {
                const result = await this.actor.addReport(await to_candid_ReportInput_n18(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Report_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReport(await to_candid_ReportInput_n18(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Report_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async createReminder(arg0: ReminderInput): Promise<Reminder> {
        if (this.processError) {
            try {
                const result = await this.actor.createReminder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReminder(arg0);
            return result;
        }
    }
    async deleteFollowUp(arg0: RecordId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFollowUp(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFollowUp(arg0);
            return result;
        }
    }
    async deleteReminder(arg0: RecordId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReminder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReminder(arg0);
            return result;
        }
    }
    async deleteReport(arg0: RecordId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReport(arg0);
            return result;
        }
    }
    async getDashboardSummary(): Promise<DashboardSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardSummary();
                return from_candid_DashboardSummary_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardSummary();
            return from_candid_DashboardSummary_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDoseHistory7Days(arg0: Timestamp): Promise<Array<DoseRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoseHistory7Days(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoseHistory7Days(arg0);
            return result;
        }
    }
    async getHealthTimeline(): Promise<Array<TimelineEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHealthTimeline();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHealthTimeline();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrescription(arg0: RecordId): Promise<Prescription | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrescription(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrescription(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReport(arg0: RecordId): Promise<Report | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReport(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReport(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUpcomingFollowUps(arg0: Timestamp): Promise<Array<FollowUp>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpcomingFollowUps(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpcomingFollowUps(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async listActiveReminders(): Promise<Array<Reminder>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActiveReminders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActiveReminders();
            return result;
        }
    }
    async listFollowUps(): Promise<Array<FollowUp>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFollowUps();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFollowUps();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPrescriptions(): Promise<Array<Prescription>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPrescriptions();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPrescriptions();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async listReports(): Promise<Array<Report>> {
        if (this.processError) {
            try {
                const result = await this.actor.listReports();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listReports();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async markFollowUpCompleted(arg0: RecordId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markFollowUpCompleted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markFollowUpCompleted(arg0);
            return result;
        }
    }
    async recordDoseTaken(arg0: RecordId, arg1: Timestamp, arg2: bigint): Promise<DoseRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.recordDoseTaken(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordDoseTaken(arg0, arg1, arg2);
            return result;
        }
    }
    async rescheduleFollowUp(arg0: RecordId, arg1: Timestamp): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.rescheduleFollowUp(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rescheduleFollowUp(arg0, arg1);
            return result;
        }
    }
    async scheduleFollowUp(arg0: FollowUpInput): Promise<FollowUp> {
        if (this.processError) {
            try {
                const result = await this.actor.scheduleFollowUp(arg0);
                return from_candid_FollowUp_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.scheduleFollowUp(arg0);
            return from_candid_FollowUp_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePrescriptionStatus(arg0: RecordId, arg1: PrescriptionStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePrescriptionStatus(arg0, to_candid_PrescriptionStatus_n45(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePrescriptionStatus(arg0, to_candid_PrescriptionStatus_n45(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateReminder(arg0: RecordId, arg1: ReminderUpdate): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReminder(arg0, to_candid_ReminderUpdate_n47(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReminder(arg0, to_candid_ReminderUpdate_n47(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
async function from_candid_DashboardSummary_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DashboardSummary): Promise<DashboardSummary> {
    return await from_candid_record_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FollowUpStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FollowUpStatus): FollowUpStatus {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_FollowUp_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FollowUp): FollowUp {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_PrescriptionStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PrescriptionStatus): PrescriptionStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
async function from_candid_Prescription_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Prescription): Promise<Prescription> {
    return await from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ReportType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportType): ReportType {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_Report_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Report): Promise<Report> {
    return await from_candid_record_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_TimelineEventKind_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimelineEventKind): Promise<TimelineEventKind> {
    return await from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
async function from_candid_TimelineEvent_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimelineEvent): Promise<TimelineEvent> {
    return await from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n17(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Prescription]): Promise<Prescription | null> {
    return value.length === 0 ? null : await from_candid_Prescription_n11(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Report]): Promise<Report | null> {
    return value.length === 0 ? null : await from_candid_Report_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RecordId;
    status: _PrescriptionStatus;
    endDate: [] | [_Timestamp];
    documentRef: [] | [_ExternalBlob];
    dosage: string;
    owner: _UserId;
    createdAt: _Timestamp;
    notes: string;
    frequency: string;
    startDate: _Timestamp;
    medicineName: string;
}): Promise<{
    id: RecordId;
    status: PrescriptionStatus;
    endDate?: Timestamp;
    documentRef?: ExternalBlob;
    dosage: string;
    owner: UserId;
    createdAt: Timestamp;
    notes: string;
    frequency: string;
    startDate: Timestamp;
    medicineName: string;
}> {
    return {
        id: value.id,
        status: from_candid_PrescriptionStatus_n13(_uploadFile, _downloadFile, value.status),
        endDate: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.endDate)),
        documentRef: record_opt_to_undefined(await from_candid_opt_n16(_uploadFile, _downloadFile, value.documentRef)),
        dosage: value.dosage,
        owner: value.owner,
        createdAt: value.createdAt,
        notes: value.notes,
        frequency: value.frequency,
        startDate: value.startDate,
        medicineName: value.medicineName
    };
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RecordId;
    owner: _UserId;
    createdAt: _Timestamp;
    reportDate: _Timestamp;
    reportType: _ReportType;
    notes: string;
    fileRef: _ExternalBlob;
}): Promise<{
    id: RecordId;
    owner: UserId;
    createdAt: Timestamp;
    reportDate: Timestamp;
    reportType: ReportType;
    notes: string;
    fileRef: ExternalBlob;
}> {
    return {
        id: value.id,
        owner: value.owner,
        createdAt: value.createdAt,
        reportDate: value.reportDate,
        reportType: from_candid_ReportType_n24(_uploadFile, _downloadFile, value.reportType),
        notes: value.notes,
        fileRef: await from_candid_ExternalBlob_n17(_uploadFile, _downloadFile, value.fileRef)
    };
}
async function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    todayReminders: Array<_Reminder>;
    recentReports: Array<_Report>;
    activePrescriptions: Array<_Prescription>;
    upcomingFollowUps: Array<_FollowUp>;
}): Promise<{
    todayReminders: Array<Reminder>;
    recentReports: Array<Report>;
    activePrescriptions: Array<Prescription>;
    upcomingFollowUps: Array<FollowUp>;
}> {
    return {
        todayReminders: value.todayReminders,
        recentReports: await from_candid_vec_n28(_uploadFile, _downloadFile, value.recentReports),
        activePrescriptions: await from_candid_vec_n29(_uploadFile, _downloadFile, value.activePrescriptions),
        upcomingFollowUps: from_candid_vec_n30(_uploadFile, _downloadFile, value.upcomingFollowUps)
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RecordId;
    status: _FollowUpStatus;
    scheduledDate: _Timestamp;
    owner: _UserId;
    createdAt: _Timestamp;
    rescheduledDate: [] | [_Timestamp];
    notes: string;
    doctorName: string;
    department: string;
}): {
    id: RecordId;
    status: FollowUpStatus;
    scheduledDate: Timestamp;
    owner: UserId;
    createdAt: Timestamp;
    rescheduledDate?: Timestamp;
    notes: string;
    doctorName: string;
    department: string;
} {
    return {
        id: value.id,
        status: from_candid_FollowUpStatus_n33(_uploadFile, _downloadFile, value.status),
        scheduledDate: value.scheduledDate,
        owner: value.owner,
        createdAt: value.createdAt,
        rescheduledDate: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.rescheduledDate)),
        notes: value.notes,
        doctorName: value.doctorName,
        department: value.department
    };
}
async function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RecordId;
    date: _Timestamp;
    kind: _TimelineEventKind;
}): Promise<{
    id: RecordId;
    date: Timestamp;
    kind: TimelineEventKind;
}> {
    return {
        id: value.id,
        date: value.date,
        kind: await from_candid_TimelineEventKind_n38(_uploadFile, _downloadFile, value.kind)
    };
}
async function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reportType: {
        lab: null;
    } | {
        other: null;
    } | {
        imaging: null;
    };
    notes: string;
    fileRef: _ExternalBlob;
}): Promise<{
    reportType: Variant_lab_other_imaging;
    notes: string;
    fileRef: ExternalBlob;
}> {
    return {
        reportType: from_candid_variant_n25(_uploadFile, _downloadFile, value.reportType),
        notes: value.notes,
        fileRef: await from_candid_ExternalBlob_n17(_uploadFile, _downloadFile, value.fileRef)
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        active: null;
    } | {
        inactive: null;
    };
    dosage: string;
    frequency: string;
    medicineName: string;
}): {
    status: PrescriptionStatus;
    dosage: string;
    frequency: string;
    medicineName: string;
} {
    return {
        status: from_candid_variant_n14(_uploadFile, _downloadFile, value.status),
        dosage: value.dosage,
        frequency: value.frequency,
        medicineName: value.medicineName
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        scheduled: null;
    } | {
        rescheduled: null;
    } | {
        completed: null;
    };
    doctorName: string;
    department: string;
}): {
    status: Variant_scheduled_rescheduled_completed;
    doctorName: string;
    department: string;
} {
    return {
        status: from_candid_variant_n34(_uploadFile, _downloadFile, value.status),
        doctorName: value.doctorName,
        department: value.department
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
}): PrescriptionStatus {
    return "active" in value ? PrescriptionStatus.active : "inactive" in value ? PrescriptionStatus.inactive : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lab: null;
} | {
    other: null;
} | {
    imaging: null;
}): Variant_lab_other_imaging {
    return "lab" in value ? Variant_lab_other_imaging.lab : "other" in value ? Variant_lab_other_imaging.other : "imaging" in value ? Variant_lab_other_imaging.imaging : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    rescheduled: null;
} | {
    completed: null;
}): Variant_scheduled_rescheduled_completed {
    return "scheduled" in value ? Variant_scheduled_rescheduled_completed.scheduled : "rescheduled" in value ? Variant_scheduled_rescheduled_completed.rescheduled : "completed" in value ? Variant_scheduled_rescheduled_completed.completed : value;
}
async function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    report: {
        reportType: {
            lab: null;
        } | {
            other: null;
        } | {
            imaging: null;
        };
        notes: string;
        fileRef: _ExternalBlob;
    };
} | {
    prescription: {
        status: {
            active: null;
        } | {
            inactive: null;
        };
        dosage: string;
        frequency: string;
        medicineName: string;
    };
} | {
    followup: {
        status: {
            scheduled: null;
        } | {
            rescheduled: null;
        } | {
            completed: null;
        };
        doctorName: string;
        department: string;
    };
}): Promise<{
    __kind__: "report";
    report: {
        reportType: Variant_lab_other_imaging;
        notes: string;
        fileRef: ExternalBlob;
    };
} | {
    __kind__: "prescription";
    prescription: {
        status: PrescriptionStatus;
        dosage: string;
        frequency: string;
        medicineName: string;
    };
} | {
    __kind__: "followup";
    followup: {
        status: Variant_scheduled_rescheduled_completed;
        doctorName: string;
        department: string;
    };
}> {
    return "report" in value ? {
        __kind__: "report",
        report: await from_candid_record_n40(_uploadFile, _downloadFile, value.report)
    } : "prescription" in value ? {
        __kind__: "prescription",
        prescription: from_candid_record_n41(_uploadFile, _downloadFile, value.prescription)
    } : "followup" in value ? {
        __kind__: "followup",
        followup: from_candid_record_n42(_uploadFile, _downloadFile, value.followup)
    } : value;
}
async function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Report>): Promise<Array<Report>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Report_n22(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Prescription>): Promise<Array<Prescription>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Prescription_n11(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FollowUp>): Array<FollowUp> {
    return value.map((x)=>from_candid_FollowUp_n31(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TimelineEvent>): Promise<Array<TimelineEvent>> {
    return await Promise.all(value.map(async (x)=>await from_candid_TimelineEvent_n36(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_PrescriptionInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PrescriptionInput): Promise<_PrescriptionInput> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_PrescriptionStatus_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PrescriptionStatus): _PrescriptionStatus {
    return to_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function to_candid_ReminderUpdate_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReminderUpdate): _ReminderUpdate {
    return to_candid_record_n48(_uploadFile, _downloadFile, value);
}
async function to_candid_ReportInput_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportInput): Promise<_ReportInput> {
    return await to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_ReportType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportType): _ReportType {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reportDate: Timestamp;
    reportType: ReportType;
    notes: string;
    fileRef: ExternalBlob;
}): Promise<{
    reportDate: _Timestamp;
    reportType: _ReportType;
    notes: string;
    fileRef: _ExternalBlob;
}> {
    return {
        reportDate: value.reportDate,
        reportType: to_candid_ReportType_n20(_uploadFile, _downloadFile, value.reportType),
        notes: value.notes,
        fileRef: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.fileRef)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dosage?: string;
    reminderTimes?: Array<bigint>;
    isActive?: boolean;
    medicineName?: string;
}): {
    dosage: [] | [string];
    reminderTimes: [] | [Array<bigint>];
    isActive: [] | [boolean];
    medicineName: [] | [string];
} {
    return {
        dosage: value.dosage ? candid_some(value.dosage) : candid_none(),
        reminderTimes: value.reminderTimes ? candid_some(value.reminderTimes) : candid_none(),
        isActive: value.isActive ? candid_some(value.isActive) : candid_none(),
        medicineName: value.medicineName ? candid_some(value.medicineName) : candid_none()
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    endDate?: Timestamp;
    documentRef?: ExternalBlob;
    dosage: string;
    notes: string;
    frequency: string;
    startDate: Timestamp;
    medicineName: string;
}): Promise<{
    endDate: [] | [_Timestamp];
    documentRef: [] | [_ExternalBlob];
    dosage: string;
    notes: string;
    frequency: string;
    startDate: _Timestamp;
    medicineName: string;
}> {
    return {
        endDate: value.endDate ? candid_some(value.endDate) : candid_none(),
        documentRef: value.documentRef ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.documentRef)) : candid_none(),
        dosage: value.dosage,
        notes: value.notes,
        frequency: value.frequency,
        startDate: value.startDate,
        medicineName: value.medicineName
    };
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_lab_other_imaging): {
    lab: null;
} | {
    other: null;
} | {
    imaging: null;
} {
    return value == Variant_lab_other_imaging.lab ? {
        lab: null
    } : value == Variant_lab_other_imaging.other ? {
        other: null
    } : value == Variant_lab_other_imaging.imaging ? {
        imaging: null
    } : value;
}
function to_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PrescriptionStatus): {
    active: null;
} | {
    inactive: null;
} {
    return value == PrescriptionStatus.active ? {
        active: null
    } : value == PrescriptionStatus.inactive ? {
        inactive: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
